### ISSUE TITLE
Can't get the gem to be recognized in the project

### ISSUE THREAD

**Issue by hayesmp** [holgersindbaek/Vendor#1]
```
application_settings_controller.rb:53:in `viewDidLoad': uninitialized constant ApplicationSettingsController::Vendor (NameError)`
```

``` ruby
source 'https://rubygems.org'
gem 'bubble-wrap'
gem 'motion-testflight'
gem 'cocoapods'
gem 'motion-cocoapods'
gem 'rm_vendor'
```

``` ruby
class ApplicationSettingsController < UIViewController

    def viewDidLoad
        super
        @month_sync = Vendor::Product.new(:name => "month_sync", :id => "com.kanban2go.sync.month")
        @year_sync = Vendor::Product.new(:name => "year_sync", :id => "com.kanban2go.sync.year")

        return self
      end
end
```

**Comment by holgersindbaek** [comment]
@hayesmp I came across a bug that did I had to update the way we did the initialisation and other things. This is how you do it now:

```
@products = Vendor::Products.new([{:name => "first_item", :id => "com.your.first_item.id"}, {:name => "second_item", :id => "com.your.second_item.id"}]) do |products|
    products.map{ |product| NSLog "Product exists?: #{product.success}" }
end
```

Check out the README.

**Comment by hayesmp** [comment]
Tried this. Still getting a `uninitialized constant Vendor`. Might try moving the module directly into the project.

**Comment by holgersindbaek** [comment]
Arhh... think you might need to say:

```
require 'vendor'
```

Let me know if that works.

**Comment by hayesmp** [comment]
It's "working" better.

Is there another framework I need besides StoreKit?

``` ruby
*** Terminating app due to uncaught exception 'NameError', reason: 'info.rb:16:in `initialize:': uninitialized constant Vendor::Info::CocoaSecurityDecoder (NameError)
    from product.rb:17:in `initialize:'
    from products.rb:36:in `block in initialize:'
    from products.rb:23:in `initialize:'
```

**Comment by holgersindbaek** [comment]
You need to do rake pod:install to install the pod dependencies (there's 1 as I remember).

**Comment by holgersindbaek** [comment]
@hayesmp Did that work for you?

**Comment by hayesmp** [comment]
I'm having gemfile/cocoapod problems now. I'll get back to you when I see it work. But that seems to be the trick...

**Comment by hayesmp** [comment]
@holgersindbaek Is there a trick to getting subscriptions to be recognized?

``` ruby
subscription_secret = 'xxxxxx...'

    Vendor::Products.new([{:name => "month_sync", :id => "com.kanban2go.sync.month", :secret => subscription_secret, :subscription => true},
                                      {:name => "year_sync", :id => "com.kanban2go.sync.year", :secret => subscription_secret, :subscription => true}]) do |products|
      products.map{ |product| NSLog "Product exists?: #{product.success}" }
    end
```

``` ruby
2014-02-13 00:45:25.788 kanban2go[87470:80b] Product exists?: false
2014-02-13 00:45:25.788 kanban2go[87470:80b] Product exists?: false
```

``` ruby
subscription_name = MY_ENV['SUBSCRIPTION_NAME'] || "subscription"
    subscription_id = MY_ENV['SUBSCRIPTION_ID'] || "com.your.subscription.id"
    subscription_secret = MY_ENV['SUBSCRIPTION_SECRET'] || "abcdefg12345"
    product_name = MY_ENV['ITEM_NAME'] || "coins"
    product_id = MY_ENV['ITEM_ID'] || "com.your.item.id"
    @products = Vendor::Products.new([{:name =>  subscription_name, :id => subscription_id, :secret => subscription_secret, :subscription => true}, {:name =>  product_name, :id => product_id}]) do |products|
      products.map{ |p| NSLog "p: #{p}" }
    end
```

**Comment by holgersindbaek** [comment]
@hayesmp Just updated the gem to 0.3.2 - think I forgot to point to one of the right pod dependencies when I last pushed.

If the product doesn't seem to exist on Apple's servers, you should get passed along an NSError as well. I've updated the README on how to check that.

Let me know if that answer your questions.

**Comment by hayesmp** [comment]
Hmm.

```
2014-02-13 13:14:41.359 kanban2go[13746:80b] Product error: Cannot connect to iTunes Store
```

I bet I can't test iap in the simulator...? It's been awhile... EDIT: Yep. Need to get back to getting `rake device` to work. Looks like I'm on the path to resolution.

Also you many want to add this to the readme:

``` ruby
products.map{ |product| NSLog "Product error: #{product.error.localizedDescription}" }
```

NSError localizedDescription gets you the actual error message.

**Comment by holgersindbaek** [comment]
Ya. Iap in simulator is a no no.   

Test it on the device :-).   

## 

All the best

Holger Sindbaek
Holgersindbaek.com

**Comment by hayesmp** [comment]
Ok. It worked once or twice and now I'm getting this crash on in my viewDidLoad method:
`'NSInvalidArgumentException', reason: 'data parameter is nil'` (no helpful line number or file given)

``` ruby
def viewDidLoad
    super
    @products=Vendor::Products.new([{:name => "month_sync", :id => "com.kanban2go.sync.month", :secret => subscription_secret, :subscription => true},
                                    {:name => "year_sync", :id => "com.kanban2go.sync.year", :secret =>     subscription_secret, :subscription => true}]) do |products|
      products.map{ |product| NSLog "Product exists?: #{product.success}" }
      products.map{ |product| NSLog "Product error: #{product.error.localizedDescription}" if product.error }
      products.map{ |product| NSLog "Product response: #{product.response}" }
    end
    @month_sync = @products[:month_sync]
    @year_sync = @products[:year_sync]

    return self
  end
```

**Comment by holgersindbaek** [comment]
Arh... I'm guessing that is happening in line 15 to 20 in info.rb.

My guess is that it is checking the receipt that is SHOULD have, but probably doesn't. Maybe it doesn't have it, because the purchase didn't fully go through the last time or maybe there just isn't any receipt.

Could be great to check for a receipt, before updating the receipt there. Can you play around with that?

**Comment by hayesmp** [comment]
Oh yeah, in the previous version of the gem I hand wrapped a conditional around the reciept code, but it was from a different failure. I'll try that again.
EDIT: Nope, that didn't work. I'll have to dig around and see where an NSURL call is getting nil data.
